### ISSUE TITLE
CheckList pra terminar

### ISSUE THREAD

**Issue by hppyft** [hppyft/tcc_tets#1]
- [x] Verificar int que tem que retornar pra salvar no sharedPreferences
- [x] Verificar se dados estao sendo salvos e restaurados
- [x] Pegar dados das outras telas (talvez precise mudar adapter)
- [x] Substituir dados dummy por dados reais
- [x] Realizar comparacao do resultado final
- [x] Realizar iteracao e definir criterio de parada e de decisao
- [x] Validar dados (fct 1 a 10) (proj 1 a 10) (cbr ver na tabela)
- [x] Mudar nome do app
- [x] Apresentar resultados na tela de resultados
- [x] Mudar FSC adicionando 1.3 e 1.4

**Comment by hppyft** [comment]
Possíveis erros a serem testados:

- [x] Possível erro ao converter o texto pra número em celulares em pt-br, por estarem sendo testados em en-us
